// Deep16 RTL core - WASM package glue.
//
// deep16_rtl_gen.js/.wasm are generated by scripts/build_rtl_wasm.sh and
// committed, so the IDE and the tests need no build step (same deal as
// wasm/pkg/). This file turns the flat C API of rtl/sim/harness.cpp into the
// same shape the wasm-bindgen core exposes, so a caller can pick a core by
// name alone:
//
//   const rtl = await initDeep16Rtl();
//   rtl.init(1048576);
//   rtl.load_program(0x0100, new Uint16Array([0x1234]));
//   rtl.step();
//   rtl.get_registers();          // Uint16Array(16), R15 = active PC
//
// Differences to the wasm-bindgen API are additive only: get_cycle_count(),
// get_delay_state(), poke(), peek(), get_step_count() and the raw debug bus
// (get/set_debug_state) exist for the IDE statistics line and the decode
// sweep, the behavioural cores simply do not have them.
import deep16RtlFactory from './deep16_rtl_gen.js';

export default async function initDeep16Rtl(options = {}) {
  const Module = await deep16RtlFactory(options);

  const malloc = Module._malloc;
  const free = Module._free;
  const heap16 = () => Module.HEAPU16;
  const heap32 = () => Module.HEAPU32;

  // Scratch buffer for the flat "write into caller memory" C functions.
  let scratch = 0;
  let scratchSize = 0;
  function reserve(bytes) {
    if (bytes > scratchSize) {
      if (scratch) free(scratch);
      scratch = malloc(bytes);
      scratchSize = bytes;
    }
    return scratch;
  }

  function copyOutU16(count) {
    const ptr = reserve(count * 2);
    return heap16().slice(ptr >> 1, (ptr >> 1) + count);
  }

  function copyOutU32(count) {
    const ptr = reserve(count * 4);
    return heap32().slice(ptr >> 2, (ptr >> 2) + count);
  }

  return {
    init: (memWords) => Module._init(memWords >>> 0),
    reset: () => Module._reset(),
    step: () => Module._step() !== 0,
    run_steps: (n) => Module._run_steps(n >>> 0) !== 0,

    load_program: (ptr, words) => {
      const src = reserve(words.length * 2);
      heap16().set(words, src >> 1);
      Module._load_program(ptr >>> 0, src, words.length);
    },
    set_registers: (regs) => {
      const src = reserve(regs.length * 2);
      heap16().set(regs, src >> 1);
      Module._set_registers(src, regs.length);
    },
    get_registers: () => {
      const ptr = reserve(32);
      Module._get_registers(ptr);
      return copyOutU16(16);
    },
    get_psw: () => Module._get_psw(),
    get_segments: () => {
      const ptr = reserve(8);
      Module._get_segments(ptr);
      return copyOutU16(4);
    },
    set_psw: (psw) => Module._set_psw(psw & 0xFFFF),
    set_segments: (cs, ds, ss, es) => Module._set_segments(cs, ds, ss, es),

    get_memory_slice: (start, count) => {
      const ptr = reserve(count * 2);
      Module._get_memory_slice(start >>> 0, count >>> 0, ptr);
      return copyOutU16(count);
    },
    get_memory_word: (addr) => Module._get_memory_word(addr >>> 0),

    kbd_push: (code) => Module._kbd_push(code & 0xFFFF),
    kbd_clear: () => Module._kbd_clear(),

    get_recent_access: () => {
      const ptr = reserve(24);
      Module._get_recent_access(ptr);
      return copyOutU32(6);
    },
    get_last_event: () => {
      const ptr = reserve(10);
      Module._get_last_event(ptr);
      return copyOutU16(5);
    },
    get_shadow_state: () => {
      const ptr = reserve(6);
      Module._get_shadow_state(ptr);
      return copyOutU16(3);
    },

    // --- RTL-only extras -------------------------------------------------
    get_cycle_count: () => Module._get_cycle_count(),
    get_delay_state: () => {
      const ptr = reserve(10);
      Module._get_delay_state(ptr);
      return copyOutU16(5);
    },
    get_step_count: () => Module._get_step_count(),
    poke: (addr, value) => Module._poke(addr >>> 0, value & 0xFFFF),
    peek: (addr) => Module._peek(addr >>> 0),
    get_debug_state: (idx) => Module._get_debug_state(idx & 0xFF),
    set_debug_state: (idx, value) => Module._set_debug_state(idx & 0xFF, value & 0xFFFF),
  };
}